### ISSUE TITLE
Top button handling

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-PHAL-plugin-mk1#12]
Mark 1 has a button acting as a push button as well as a potentiometer.

This button should be handle to maybe
- Trigger the recording when pushed
- Manage the volume up/down when the button is rotated

**Comment by JarbasAl** [comment]
both of those are supposed to be there and working

**Comment by goldyfruit** [comment]
Indeed... sorry for the noise.
